title: João Sousa  # Add a space after the period

logo: ghibli_Joao.png #Joao_bio.png # Use a relative path to logo image 

description: AI Researcher and Engineer. # Fix hyphenation 

show_downloads: false # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

google_site_verification: "" # Verify ownership through Search Console  

email: jpsousa.ai.96@gmail.com # Allow visitors to contact you
